language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
#    - sudo add-apt-repository --yes "deb http://download.opensuse.org/repositories/home:/benlau/xUbuntu_15.10 ./"
#    - sudo apt-get update -qq
#    - sudo apt-get install --force-yes -qq  qpm
    - export GOPATH=`pwd`/bin
    - export PATH=`pwd`/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - ./qtci/env/qt-5.7
    - source qt-5.7.env
    - mkdir build
    - cd build
    - run-unittests ../tests/sparkqmltests/sparktests.pro

